robot_cfg:
    kinematics:
        use_usd_kinematics: false
        urdf_path: robot/unitree_inspire/g1_29dof_with_inspire_hand.urdf
        asset_root_path: robot/unitree_inspire
        isaac_usd_path: null
        usd_robot_root: g1_29dof_with_inspire_hand
        usd_path: null
        base_link: "pelvis"
        ee_link: "L_hand_base_link" 
        link_names: [
            "L_hand_base_link",
            "L_thumb_distal",
            "L_index_intermediate",
            "L_middle_intermediate",
            "L_ring_intermediate",
            "L_pinky_intermediate",
        ]

        # lock_joints: {"waist_yaw_joint": 0.0, "waist_roll_joint": 0.0, "waist_pitch_joint": 0.0}
        extra_links: null

        collision_link_names: [
            "left_shoulder_pitch_link",
            "left_shoulder_roll_link",
            "left_shoulder_yaw_link",
            "left_elbow_link",
            "left_wrist_pitch_link",
            
            "torso_link",

            "right_shoulder_pitch_link",
            "right_shoulder_roll_link",
            "right_shoulder_yaw_link",
            "right_elbow_link",
            "right_wrist_pitch_link",

            "L_hand_base_link",
            "L_thumb_proximal_base",
            "L_thumb_proximal",
            "L_thumb_intermediate",
            "L_thumb_distal",
            "L_index_proximal",
            "L_index_intermediate",
            "L_middle_proximal",
            "L_middle_intermediate",
            "L_ring_proximal",
            "L_ring_intermediate",
            "L_pinky_proximal",
            "L_pinky_intermediate",
            
            "R_hand_base_link",
            "R_thumb_proximal_base",
            "R_thumb_proximal",
            "R_thumb_intermediate",
            "R_thumb_distal",
            "R_index_proximal",
            "R_index_intermediate",
            "R_middle_proximal",
            "R_middle_intermediate",
            "R_ring_proximal",
            "R_ring_intermediate",
            "R_pinky_proximal",
            "R_pinky_intermediate",
        ]
        collision_spheres: spheres/g1_29dof_inspire.yml
        collision_sphere_buffer: 0.005
        extra_collision_spheres: {}
        
        self_collision_ignore: {
            "left_shoulder_pitch_link": [
                "left_shoulder_pitch_link",
                "left_shoulder_roll_link",
                "left_shoulder_yaw_link",
                "left_elbow_link",
                "left_wrist_pitch_link",
                "torso_link",
            ],
            "left_shoulder_roll_link": [
                "left_shoulder_pitch_link",
                "left_shoulder_roll_link",
                "left_shoulder_yaw_link",
                "left_elbow_link",
                "left_wrist_pitch_link",
                "torso_link",
            ],
            "left_shoulder_yaw_link": [
                "left_shoulder_pitch_link",
                "left_shoulder_roll_link",
                "left_shoulder_yaw_link",
                "left_elbow_link",
                "left_wrist_pitch_link",
            ],
            "left_elbow_link": [
                "left_shoulder_pitch_link",
                "left_shoulder_roll_link",
                "left_shoulder_yaw_link",
                "left_elbow_link",
                "left_wrist_pitch_link",
                
            ],
            "left_wrist_pitch_link": [
                "left_shoulder_pitch_link",
                "left_shoulder_roll_link",
                "left_shoulder_yaw_link",
                "left_elbow_link",
                "left_wrist_pitch_link",
                
            ],
            "torso_link": [
                "left_shoulder_pitch_link",
                "left_shoulder_roll_link",
                "right_shoulder_pitch_link",
                "right_shoulder_roll_link",
            ],
            "right_shoulder_pitch_link": [
                "right_shoulder_pitch_link",
                "right_shoulder_roll_link",
                "right_shoulder_yaw_link",
                "right_elbow_link",
                "right_wrist_pitch_link",
                "torso_link",
            ],
            "right_shoulder_roll_link": [
                "right_shoulder_pitch_link",
                "right_shoulder_roll_link",
                "right_shoulder_yaw_link",
                "right_elbow_link",
                "right_wrist_pitch_link",
                "torso_link",
            ],
            "right_shoulder_yaw_link": [
                "right_shoulder_pitch_link",
                "right_shoulder_roll_link",
                "right_shoulder_yaw_link",
                "right_elbow_link",
                "right_wrist_pitch_link",
            ],
            "right_elbow_link": [
                "right_shoulder_pitch_link",
                "right_shoulder_roll_link",
                "right_shoulder_yaw_link",
                "right_elbow_link",
                "right_wrist_pitch_link",
            ],
            "right_wrist_pitch_link": [
                "right_shoulder_pitch_link",
                "right_shoulder_roll_link",
                "right_shoulder_yaw_link",
                "right_elbow_link",
                "right_wrist_pitch_link",
            ],

            "L_hand_base_link": [
                "L_hand_base_link",
                "L_thumb_distal",
                "L_index_intermediate",
                "L_middle_intermediate",
                "L_ring_intermediate",
                "L_pinky_intermediate",
            ],
            "L_thumb_proximal_base": [
                "L_hand_base_link",
                "L_thumb_distal",
                "L_index_intermediate",
                "L_middle_intermediate",
                "L_ring_intermediate",
                "L_pinky_intermediate",
            ],
            "L_thumb_proximal": [
                "L_hand_base_link",
                "L_thumb_distal",
                "L_index_intermediate",
                "L_middle_intermediate",
                "L_ring_intermediate",
                "L_pinky_intermediate",
            ],
            "L_thumb_intermediate": [
                "L_hand_base_link",
                "L_thumb_distal",
                "L_index_intermediate",
                "L_middle_intermediate",
                "L_ring_intermediate",
                "L_pinky_intermediate",
            ],
            "L_thumb_distal": [
                "L_hand_base_link",
                "L_thumb_distal",
                "L_index_intermediate",
                "L_middle_intermediate",
                "L_ring_intermediate",
                "L_pinky_intermediate",
            ],
            "L_index_proximal": [
                "L_hand_base_link",
                "L_thumb_distal",
                "L_index_intermediate",
                "L_middle_intermediate",
                "L_ring_intermediate",
                "L_pinky_intermediate",
            ],
            "L_index_intermediate": [
                "L_hand_base_link",
                "L_thumb_distal",
                "L_index_intermediate",
                "L_middle_intermediate",
                "L_ring_intermediate",
                "L_pinky_intermediate",
            ],
            "L_middle_proximal": [
                "L_hand_base_link",
                "L_thumb_distal",
                "L_index_intermediate",
                "L_middle_intermediate",
                "L_ring_intermediate",
                "L_pinky_intermediate",
            ],
            "L_middle_intermediate": [
                "L_hand_base_link",
                "L_thumb_distal",
                "L_index_intermediate",
                "L_middle_intermediate",
                "L_ring_intermediate",
                "L_pinky_intermediate",
            ],
            "L_ring_proximal": [
                "L_hand_base_link",
                "L_thumb_distal",
                "L_index_intermediate",
                "L_middle_intermediate",
                "L_ring_intermediate",
                "L_pinky_intermediate",
            ],
            "L_ring_intermediate": [
                "L_hand_base_link",
                "L_thumb_distal",
                "L_index_intermediate",
                "L_middle_intermediate",
                "L_ring_intermediate",
                "L_pinky_intermediate",
            ],
            "L_pinky_proximal": [
                "L_hand_base_link",
                "L_thumb_distal",
                "L_index_intermediate",
                "L_middle_intermediate",
                "L_ring_intermediate",
                "L_pinky_intermediate",
            ],
            "L_pinky_intermediate": [
                "L_hand_base_link",
                "L_thumb_distal",
                "L_index_intermediate",
                "L_middle_intermediate",
                "L_ring_intermediate",
                "L_pinky_intermediate",
            ],

            "R_hand_base_link": [
                "R_hand_base_link",
                "R_thumb_distal",
                "R_index_intermediate",
                "R_middle_intermediate",
                "R_ring_intermediate",
                "R_pinky_intermediate",
            ],
            "R_thumb_proximal_base": [
                "R_hand_base_link",
                "R_thumb_distal",
                "R_index_intermediate",
                "R_middle_intermediate",
                "R_ring_intermediate",
                "R_pinky_intermediate",
            ],
            "R_thumb_proximal": [
                "R_hand_base_link",
                "R_thumb_distal",
                "R_index_intermediate",
                "R_middle_intermediate",
                "R_ring_intermediate",
                "R_pinky_intermediate",
            ],
            "R_thumb_intermediate": [
                "R_hand_base_link",
                "R_thumb_distal",
                "R_index_intermediate",
                "R_middle_intermediate",
                "R_ring_intermediate",
                "R_pinky_intermediate",
            ],
            "R_thumb_distal": [
                "R_hand_base_link",
                "R_thumb_distal",
                "R_index_intermediate",
                "R_middle_intermediate",
                "R_ring_intermediate",
                "R_pinky_intermediate",
            ],
            "R_index_proximal": [
                "R_hand_base_link",
                "R_thumb_distal",
                "R_index_intermediate",
                "R_middle_intermediate",
                "R_ring_intermediate",
                "R_pinky_intermediate",
            ],
            "R_index_intermediate": [
                "R_hand_base_link",
                "R_thumb_distal",
                "R_index_intermediate",
                "R_middle_intermediate",
                "R_ring_intermediate",
                "R_pinky_intermediate",
            ],
            "R_middle_proximal": [
                "R_hand_base_link",
                "R_thumb_distal",
                "R_index_intermediate",
                "R_middle_intermediate",
                "R_ring_intermediate",
                "R_pinky_intermediate",
            ],
            "R_middle_intermediate": [
                "R_hand_base_link",
                "R_thumb_distal",
                "R_index_intermediate",
                "R_middle_intermediate",
                "R_ring_intermediate",
                "R_pinky_intermediate",
            ],
            "R_ring_proximal": [
                "R_hand_base_link",
                "R_thumb_distal",
                "R_index_intermediate",
                "R_middle_intermediate",
                "R_ring_intermediate",
                "R_pinky_intermediate",
            ],
            "R_ring_intermediate": [
                "R_hand_base_link",
                "R_thumb_distal",
                "R_index_intermediate",
                "R_middle_intermediate",
                "R_ring_intermediate",
                "R_pinky_intermediate",
            ],
            "R_pinky_proximal": [
                "R_hand_base_link",
                "R_thumb_distal",
                "R_index_intermediate",
                "R_middle_intermediate",
                "R_ring_intermediate",
                "R_pinky_intermediate",
            ],
            "R_pinky_intermediate": [
                "R_hand_base_link",
                "R_thumb_distal",
                "R_index_intermediate",
                "R_middle_intermediate",
                "R_ring_intermediate",
                "R_pinky_intermediate",
            ],
        } # Dict[str, List[str]]
        
        self_collision_buffer: {
            "left_shoulder_pitch_link": 0.0,
            "left_shoulder_roll_link": 0.0,
            "left_shoulder_yaw_link": 0.0,
            "left_elbow_link": 0.0,
            "left_wrist_pitch_link": 0.0,
            "torso_link": 0.0,
            "right_shoulder_pitch_link": 0.0,
            "right_shoulder_roll_link": 0.0,
            "right_shoulder_yaw_link": 0.0,
            "right_elbow_link": 0.0,
            "right_wrist_pitch_link": 0.0,

            "L_hand_base_link": 0.0,
            "L_thumb_proximal_base": 0.0,
            "L_thumb_proximal": 0.0,
            "L_thumb_intermediate": 0.0,
            "L_thumb_distal": 0.0,
            "L_index_proximal": 0.0,
            "L_index_intermediate": 0.0,
            "L_middle_proximal": 0.0,
            "L_middle_intermediate": 0.0,
            "L_ring_proximal": 0.0,
            "L_ring_intermediate": 0.0,
            "L_pinky_proximal": 0.0,
            "L_pinky_intermediate": 0.0,

            "R_hand_base_link": 0.0,
            "R_thumb_proximal_base": 0.0,
            "R_thumb_proximal": 0.0,
            "R_thumb_intermediate": 0.0,
            "R_thumb_distal": 0.0,
            "R_index_proximal": 0.0,
            "R_index_intermediate": 0.0,
            "R_middle_proximal": 0.0,
            "R_middle_intermediate": 0.0,
            "R_ring_proximal": 0.0,
            "R_ring_intermediate": 0.0,
            "R_pinky_proximal": 0.0,
            "R_pinky_intermediate": 0.0,
        } # Dict[str, float]

        use_global_cumul: True
        mesh_link_names: [
            "left_hip_pitch_link",
            "left_hip_roll_link",
            "left_hip_yaw_link",
            "left_knee_link",
            "left_ankle_pitch_link",
            'left_ankle_roll_link', 
            
            'right_hip_pitch_link',
            'right_hip_roll_link', 
            'right_hip_yaw_link',
            'right_knee_link', 
            'right_ankle_pitch_link', 
            'right_ankle_roll_link', 
            
            'waist_yaw_link', 
            'waist_roll_link', 
            # 'waist_pitch_link', 
            "torso_link",
            
            'left_shoulder_pitch_link', 
            'left_shoulder_roll_link', 
            'left_shoulder_yaw_link', 
            'left_elbow_link', 
            'left_wrist_roll_link', 
            'left_wrist_pitch_link', 
            'left_wrist_yaw_link', 

            'right_shoulder_pitch_link', 
            'right_shoulder_roll_link', 
            'right_shoulder_yaw_link', 
            'right_elbow_link', 
            'right_wrist_roll_link', 
            'right_wrist_pitch_link', 
            'right_wrist_yaw_link',

            "L_hand_base_link",
            "L_thumb_proximal_base",
            "L_thumb_proximal",
            "L_thumb_intermediate",
            "L_thumb_distal",
            "L_index_proximal",
            "L_index_intermediate",
            "L_middle_proximal",
            "L_middle_intermediate",
            "L_ring_proximal",
            "L_ring_intermediate",
            "L_pinky_proximal",
            "L_pinky_intermediate",
            
            "R_hand_base_link",
            "R_thumb_proximal_base",
            "R_thumb_proximal",
            "R_thumb_intermediate",
            "R_thumb_distal",
            "R_index_proximal",
            "R_index_intermediate",
            "R_middle_proximal",
            "R_middle_intermediate",
            "R_ring_proximal",
            "R_ring_intermediate",
            "R_pinky_proximal",
            "R_pinky_intermediate",
        ] # List[str]

        cspace:
            joint_names: [
                "left_hip_pitch_joint",
                "left_hip_roll_joint",
                "left_hip_yaw_joint",
                "left_knee_joint",
                "left_ankle_pitch_joint",
                'left_ankle_roll_joint', 
                
                'right_hip_pitch_joint',
                'right_hip_roll_joint', 
                'right_hip_yaw_joint',
                'right_knee_joint', 
                'right_ankle_pitch_joint', 
                'right_ankle_roll_joint', 
                
                'waist_yaw_joint', 
                'waist_roll_joint', 
                'waist_pitch_joint', 
                
                'left_shoulder_pitch_joint', 
                'left_shoulder_roll_joint', 
                'left_shoulder_yaw_joint', 
                'left_elbow_joint', 
                'left_wrist_roll_joint', 
                'left_wrist_pitch_joint', 
                'left_wrist_yaw_joint', 
                'right_shoulder_pitch_joint', 
                
                'right_shoulder_roll_joint', 
                'right_shoulder_yaw_joint', 
                'right_elbow_joint', 
                'right_wrist_roll_joint', 
                'right_wrist_pitch_joint', 
                'right_wrist_yaw_joint',

                'L_thumb_proximal_yaw_joint', 
                'L_thumb_proximal_pitch_joint', 
                'L_index_proximal_joint', 
                'L_middle_proximal_joint', 
                'L_ring_proximal_joint', 
                'L_pinky_proximal_joint', 
                
                'R_thumb_proximal_yaw_joint', 
                'R_thumb_proximal_pitch_joint', 
                'R_index_proximal_joint', 
                'R_middle_proximal_joint', 
                'R_ring_proximal_joint', 
                'R_pinky_proximal_joint'
            ] # List[str]

            retract_config: [0,0,0,0,0,0,
                            0,0,0,0,0,0,
                            0,0,0,
                            0,0,0,0,0,0,0,
                            0,0,0,0,0,0,0,
                            0,0,0,0,0,0,
                            0,0,0,0,0,0] # List[float]
            null_space_weight: [1.0,1.0,1.0,1.0,1.0,1.0,
                               1.0,1.0,1.0,1.0,1.0,1.0,
                               1.0,1.0,1.0,
                               1.0,1.0,1.0,1.0,1.0,1.0,1.0,
                               1.0,1.0,1.0,1.0,1.0,1.0,1.0,
                               1.0,1.0,1.0,1.0,1.0,1.0,
                               1.0,1.0,1.0,1.0,1.0,1.0] # List[float]
            cspace_distance_weight: [1.0,1.0,1.0,1.0,1.0,1.0,
                                     1.0,1.0,1.0,1.0,1.0,1.0,
                                     1.0,1.0,1.0,
                                     1.0,1.0,1.0,1.0,1.0,1.0,1.0,
                                     1.0,1.0,1.0,1.0,1.0,1.0,1.0,
                                     1.0,1.0,1.0,1.0,1.0,1.0,
                                     1.0,1.0,1.0,1.0,1.0,1.0] # List[float]
            max_jerk: 500.0
            max_acceleration: 15.0