collision_spheres:
  left_shoulder_pitch_link:
    - "center": [-0.0, 0.04, -0.014]
      "radius": 0.04007
  left_shoulder_roll_link:
    - "center": [-0.001, 0.006, -0.08]
      "radius": 0.0326
    - "center": [0.012, 0.0, -0.056]
      "radius": 0.02
    - "center": [-0.006, 0.021, -0.059]
      "radius": 0.02
  left_shoulder_yaw_link:
    - "center": [0.011, -0.0, -0.081]
      "radius": 0.04284
    - "center": [-0.015, 0.002, -0.027]
      "radius": 0.03932
  left_elbow_link:
    - "center": [0.071, 0.002, -0.011]
      "radius": 0.03819
    - "center": [0.06, 0.015, -0.01]
      "radius": 0.02934
  left_wrist_pitch_link:
    - "center": [0.053, -0.001, -0.001]
      "radius": 0.03112
    - "center": [-0.003, -0.001, 0.003]
      "radius": 0.03112
  torso_link:
    - "center": [-0.01, -0.0, 0.13]
      "radius": 0.105
  right_shoulder_pitch_link:
    - "center": [-0.0, -0.038, -0.016]
      "radius": 0.04007
  right_shoulder_roll_link:
    - "center": [0.001, -0.006, -0.08]
      "radius": 0.0326
    - "center": [0.002, -0.011, -0.065]
      "radius": 0.02923
    - "center": [-0.008, -0.002, -0.061]
      "radius": 0.02518
  right_shoulder_yaw_link:
    - "center": [0.015, 0.003, -0.084]
      "radius": 0.03284
    - "center": [-0.006, 0.001, -0.019]
      "radius": 0.03284
  right_elbow_link:
    - "center": [0.071, -0.002, -0.011]
      "radius": 0.03819
  right_wrist_pitch_link:
    - "center": [0.006, 0.001, 0.001]
      "radius": 0.03112
    - "center": [0.049, -0.002, -0.001]
      "radius": 0.03112


  left_hand_palm_link:
  - "center": [0.055, -0.007, 0.0]
    "radius": 0.01
  - "center": [0.055, -0.007, 0.025]
    "radius": 0.01
  - "center": [0.055, -0.007, -0.025]
    "radius": 0.01
  
  # Thumb base link - 1 sphere at joint
  left_hand_thumb_0_link:
  - "center": [-0.001, -0.02, 0.0]
    "radius": 0.01
  
  # Thumb proximal link - 2 spheres along segment
  left_hand_thumb_1_link:
  - "center": [-0.0012, -0.045, 0.0]
    "radius": 0.01
  - "center": [-0.0012, -0.025, 0.0]
    "radius": 0.01
  
  # Thumb distal link (fingertip) - 1 sphere
  left_hand_thumb_2_link:
  - "center": [-0.0015, -0.025, 0.0]
    "radius": 0.01
  
  # Middle finger proximal - 2 spheres
  left_hand_middle_0_link:
  - "center": [0.0, -0.001, 0.0]
    "radius": 0.01
  - "center": [0.025, 0.0, 0.0]
    "radius": 0.01
  
  # Middle finger distal (fingertip) - 2 spheres
  left_hand_middle_1_link:
  - "center": [0.0, 0.0015, 0.0]
    "radius": 0.01
  - "center": [0.03, 0.002, 0.0]
    "radius": 0.01
  
  # Index finger proximal - 2 spheres
  left_hand_index_0_link:
  - "center": [0.0, -0.001, 0.0]
    "radius": 0.01
  - "center": [0.025, 0.0, 0.0]
    "radius": 0.01
  
  # Index finger distal (fingertip) - 2 spheres
  left_hand_index_1_link:
  - "center": [0.0, 0.0015, 0.0]
    "radius": 0.01
  - "center": [0.03, 0.002, 0.0]
    "radius": 0.01

  right_hand_palm_link:
  - "center": [0.055, 0.007, 0.0]
    "radius": 0.01
  - "center": [0.055, 0.007, 0.025]
    "radius": 0.01
  - "center": [0.055, 0.007, -0.025]
    "radius": 0.01
  
  # Thumb base link - 1 sphere at joint
  right_hand_thumb_0_link:
  - "center": [-0.001, 0.02, 0.0]
    "radius": 0.01
  
  # Thumb proximal link - 2 spheres along segment
  right_hand_thumb_1_link:
  - "center": [-0.0012, 0.025, 0.0]
    "radius": 0.01
  - "center": [-0.0012, 0.045, 0.0]
    "radius": 0.01
  
  # Thumb distal link (fingertip) - 1 sphere
  right_hand_thumb_2_link:
  - "center": [-0.0015, 0.025, 0.0]
    "radius": 0.01
  # - "center": [-0.0015, 0.045, 0.0]
  #   "radius": 0.01
  
  
  # Middle finger proximal - 2 spheres
  right_hand_middle_0_link:
  - "center": [0.0, 0.001, 0.0]
    "radius": 0.01
  - "center": [0.025, 0.0, 0.0]
    "radius": 0.01
  
  # Middle finger distal (fingertip) - 2 spheres
  right_hand_middle_1_link:
  - "center": [0.0, -0.0015, 0.0]
    "radius": 0.01
  - "center": [0.03, -0.002, 0.0]
    "radius": 0.01
  - "center": [0.04, -0.002, 0.0]
    "radius": 0.005
  
  
  # Index finger proximal - 2 spheres
  right_hand_index_0_link:
  - "center": [0.0, 0.001, 0.0]
    "radius": 0.01
  - "center": [0.025, 0.0, 0.0]
    "radius": 0.01
  
  # Index finger distal (fingertip) - 2 spheres
  right_hand_index_1_link:
  - "center": [0.0, -0.0015, 0.0]
    "radius": 0.01
  - "center": [0.03, -0.002, 0.0]
    "radius": 0.01
  - "center": [0.04, -0.002, 0.0]
    "radius": 0.005